#!/home/ben/software/install/bin/perl
use warnings;
use strict;
use utf8;
use FindBin '$Bin';
use File::Slurper qw!read_text write_text!;
use Convert::Moji 'make_regex';
use Deploy 'do_system';
my $verbose;
chdir $Bin or die $!;
do_system ("./make-edit-distance-c.pl;make -f makeitfile text-fuzzy.c > /dev/null", $verbose);

my @cfiles = qw!ed-trans-char.c ed-trans-int.c edit-distance-char.c edit-distance-int.c!;
my $tfbase = "$Bin/text-fuzzy";
my $tffile = "$tfbase.c";
my $tfhfile = "$tfbase.h";
my $cfgfile = "$Bin/config.h";
for my $file ($tffile, @cfiles) {
    if (! -f $file) {
	warn "No file $file";
    }
}
my %ctexts;
for my $file (@cfiles) {
    my $txt = read_text ($file);
    # Blank all the includes.
    $txt =~ s!(#include.*)!/* $1 */!g;
    # Make all the functions static.
    $txt =~ s!^int!static int!gsm;
    my $base = $file;
    $base =~ s/\.c$//;
    $ctexts{$base} = $txt;
}
my $regex = make_regex (keys %ctexts);
my $tftext = read_text ($tffile);
my $tfh = read_text ($tfhfile);
my $cfgh = read_text ($cfgfile);
$tftext =~ s/#include\s*"text-fuzzy.h"/#line 1 "$tfhfile"\n$tfh/;
$tftext =~ s/#include\s*"config.h"/#line 1 "$cfgfile"\n$cfgh/;
$tftext =~ s/#include\s*"($regex).h"/$ctexts{$1}/g;
my $tfout = "$tfbase-single.c";
my $cfiles = join ', ', @cfiles;
my $head = <<EOF;
/*
This file was generated by $0
from $tffile,
$cfiles, and
$tfhfile.
*/
#line 1 "text-fuzzy.c"
EOF
$tftext = $head . $tftext;
write_text ($tfout, $tftext);
